### PR TITLE
Append SwiftMockConfiguration module for correct engine configuration

### LINKED ISSUE #55: `verify` doesn't fail the test
I noticed that `verify` doesn't fail the test when the call count doesn't match. I eventually figured out that there's a global closure variable, `testFailureReport`,  that `verify` calls to report a test failure. But the `testFailureReport` closure by default doesn't do anything. What's the reason for this? I also haven't found this mentioned in the documentation, that one needs to set `testFailureReport` to something useful.

### LINKED ISSUE #56: Add configuration section in documentation
Add section that will be explain configuration process of the engine.

Why there is need `continueAfterFailure`?
How to setup `verify`?
How to clean `InOrder` history?

### PR DESCRIPTION
**Pull request by MetalheadSanya**
fixes #56, fixes #55

### CODE REVIEW

File: Tests/SwiftMockTests/PropertyStubbingTests.swift [hunk 1]
```diff
@@ -29,9 +30,11 @@ protocol AsyncThrowsGetPropertyProtocol {
...
 	override func setUp() {
 		continueAfterFailure = false
-		testFailureReport = { message in
-			XCTFail(message)
-		}
+		SwiftMockConfiguration.setUp()
+	}
+	
+	override func tearDown() {
+		SwiftMockConfiguration.tearDown()
```
Comment (doobnet) [inline Tests/SwiftMockTests/PropertyStubbingTests.swift:37]: `super.tearDown()` is not called here, is that intentional?

Comment (MetalheadSanya) [reply Tests/SwiftMockTests/PropertyStubbingTests.swift:37]: No, but it doesn't change anything in this case, so it's not very important
